title: CMSForNerd :: LAB
description: PHP 8.4 LABORATORY // STRICT MODE
theme: jekyll-theme-primer
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .github/
  - roles/
  - group_vars/
  - inventory/
  - site.yml
  - ansible.cfg
  - LICENSE
  - README.md
