title: "SongketMail :: LAB"
description: "Secure Email Server Fabric // Podman 5+ & Systemd Quadlet"
theme: jekyll-theme-primer
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .github/
  - roles/
  - group_vars/
  - inventory/
  - site.yml
  - ansible.cfg
  - LICENSE
  - README.md
  - asimp_hardening_playbook.yml
  - templates/
