---
- name: Hardening, Host Preparation and Podman 5+ Email Server Deployment
  hosts: email_servers
  become: "{{ not (is_limited_environment | default(false) | bool) }}"
  tasks:
    - name: Run Host Preparation and Hardening
      ansible.builtin.import_role:
        name: host_prepare

    - name: Run Rootless Podman Quadlet Deployment
      ansible.builtin.import_role:
        name: podman_quadlet
      vars:
        ansible_become: "{{ not (is_limited_environment | default(false) | bool) }}"
        ansible_become_user: "{{ songketmail_user }}"
