---
- name: Verify Ceph Deployment Configuration
  hosts: all
  gather_facts: false
  tasks:
    - name: Verify Ceph deploy configuration files exist
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/../../playbook.yml"
      register: ceph_playbook_stat
      delegate_to: localhost

    - name: Assert Ceph deployment playbook exists
      ansible.builtin.assert:
        that:
          - ceph_playbook_stat.stat.exists
        fail_msg: "Ceph deployment playbook.yml does not exist."
